ORACLE_USER="CUSTOM_STG_ADW"
ORACLE_DSN="nonprodidsadb_low"
TNS_ADMIN="/mnt/fss-rodn-iad-odi-fs/POC/config/wallet_nonprodidsadb"
TARGET_TABLE="CUSTOM_STG_ADW.DM_STG_FORECAST_MASTER_BLOB"
INPUT_DIR="/mnt/fss-rodn-iad-odi-fs/POC/Input/Nike/Apparel"
PY_SCRIPT="/mnt/fss-rodn-iad-odi-fs/POC/nike_all_lobs_blob_data_to_adw_hist_load.py"
LOG_DIR="/mnt/fss-rodn-iad-odi-fs/POC/logs"
FLUSH_EVERY_ROWS="100000"
