ORACLE_USER="CUSTOM_STG_ADW"
ORACLE_DSN="nonprodidsadb_low"
TNS_ADMIN="/mnt/fss-rodn-iad-odi-fs/POC/config/wallet_nonprodidsadb"
TARGET_TABLE="CUSTOM_STG_ADW.DM_STG_BOM_USAGE"
INPUT_DIR="/mnt/fss-rodn-iad-odi-fs/POC/Input/Nike"
PROCESS_ALL_FILES="Y"
